name: terraform
on: [push]
jobs:
  check-format:
    name: Terraform Format Check
    runs-on: ubuntu-latest
    container: hashicorp/terraform
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Terraform Format Check
        run: terraform fmt -check -recursive -diff

  security-check:
    name: Terraform Security Check (tfsec)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Terraform Security Check (tfsec)
        uses: aquasecurity/tfsec-sarif-action@v0.0.6

  validate:
    name: Terraform Validate (examples/test)
    runs-on: ubuntu-latest
    container: hashicorp/terraform
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Terraform Init
        run: terraform init
        working-directory: examples/test
      - name: Terraform Validate
        run: terraform validate
        working-directory: examples/test

  mock-plan:
    name: Terraform Mock Plan (examples/test)
    runs-on: ubuntu-latest
    container: hashicorp/terraform
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Terraform Init
        run: terraform init
        working-directory: examples/test
      - name: Terraform Plan (Mock)
        run: terraform plan
        working-directory: examples/test
