name: terraform
on: [push]
jobs:
  check-format:
    runs-on: ubuntu-latest
    container: hashicorp/terraform
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Terraform Format Check
        run: terraform fmt -check -recursive -diff

  security-check:
    name: tfsec sarif report
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Terraform Security Check (tfsec)
        uses: tfsec/tfsec-sarif-action@main
        with:
          sarif_file: tfsec.sarif         
      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: tfsec.sarif

  validate:
    runs-on: ubuntu-latest
    container: hashicorp/terraform
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Terraform Init
        run: terraform init
        working-directory: examples/test
      - name: Terraform Validate
        run: terraform validate
        working-directory: examples/test

  mock-plan:
    runs-on: ubuntu-latest
    container: hashicorp/terraform
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Terraform Init
        run: terraform init
        working-directory: examples/test
      - name: Terraform Plan (Mock)
        run: terraform plan
        working-directory: examples/test
